# Generated by Django 5.2 on 2025-12-13 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provedor', '0002_alter_proveedor_correo_electronico'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustanciaExperimental',
            fields=[
                ('idsustanciaExperimental', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sustancia', models.CharField(max_length=45, unique=True)),
                ('tipo', models.CharField(choices=[('analgésico', 'Analgésico'), ('antibiótico', 'Antibiótico'), ('antiinflamatorio', 'Antiinflamatorio'), ('anestésico', 'Anestésico'), ('antiséptico', 'Antiséptico'), ('otro', 'Otro')], max_length=25)),
                ('concentracion', models.DecimalField(decimal_places=2, help_text='Porcentaje de concentración (0-100%)', max_digits=5)),
                ('presentacion', models.CharField(choices=[('polvo', 'Polvo'), ('líquido', 'Líquido'), ('cápsula', 'Cápsula'), ('comprimido', 'Comprimido'), ('inyectable', 'Inyectable'), ('otro', 'Otro')], max_length=45)),
                ('unidad_medida', models.CharField(choices=[('mg', 'Miligramo'), ('ml', 'Mililitro'), ('g', 'Gramo'), ('l', 'Litro'), ('µg', 'Microgramo'), ('unidad', 'Unidad')], max_length=45)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustancias', to='provedor.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Sustancias Experimentales',
                'ordering': ['nombre_sustancia'],
                'indexes': [models.Index(fields=['nombre_sustancia'], name='sustanciaEx_nombre__892ef5_idx'), models.Index(fields=['tipo'], name='sustanciaEx_tipo_1fa07e_idx'), models.Index(fields=['proveedor'], name='sustanciaEx_proveed_e94d5d_idx')],
            },
        ),
    ]
