# Generated by Django 5.2 on 2025-12-16 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provedor', '0002_alter_proveedor_correo_electronico'),
        ('sustanciaExperimental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sustanciaexperimental',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='sustanciaexperimental',
            name='sustanciaEx_nombre__892ef5_idx',
        ),
        migrations.RemoveIndex(
            model_name='sustanciaexperimental',
            name='sustanciaEx_tipo_1fa07e_idx',
        ),
        migrations.RemoveIndex(
            model_name='sustanciaexperimental',
            name='sustanciaEx_proveed_e94d5d_idx',
        ),
        migrations.RemoveField(
            model_name='sustanciaexperimental',
            name='concentracion',
        ),
        migrations.RemoveField(
            model_name='sustanciaexperimental',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='sustanciaexperimental',
            name='consentracion',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='sustanciaexperimental',
            name='nombre_sustancia',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='sustanciaexperimental',
            name='presentacion',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='sustanciaexperimental',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provedor.proveedor'),
        ),
        migrations.AlterField(
            model_name='sustanciaexperimental',
            name='tipo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sustanciaexperimental',
            name='unidad_medida',
            field=models.CharField(max_length=45),
        ),
    ]
