# Generated by Django 5.2 on 2026-01-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustanciaExperimental', '0002_alter_sustanciaexperimental_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustanciaexperimental',
            name='presentacion',
            field=models.CharField(choices=[('solida', 'Sólida'), ('semisolida', 'Semisólida'), ('liquida', 'Líquida')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sustanciaexperimental',
            name='unidad_medida',
            field=models.CharField(choices=[('g', 'gramos (g)'), ('mg', 'miligramos (mg)'), ('L', 'litros (L)'), ('ml', 'mililitros (ml)')], max_length=5),
        ),
    ]
