# Generated by Django 5.2 on 2025-12-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correo_electronico',
            field=models.EmailField(max_length=55),
        ),
    ]
