# Generated by Django 5.2 on 2026-09-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provedor', '0002_alter_proveedor_correo_electronico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
