# Generated by Django 5.2 on 2025-12-11 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provedor', '0002_alter_proveedor_correo_electronico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idmateriales', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('material_fabricacion', models.CharField(max_length=45)),
                ('piezas_disponibles', models.IntegerField()),
                ('uso', models.CharField(max_length=45)),
                ('is_active', models.BooleanField(default=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provedor.proveedor')),
            ],
        ),
    ]
