# Generated by Django 5.2 on 2026-08-03 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
        ('usuario', '0016_rename_notificaciones_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraMaterialesEliminados',
            fields=[
                ('idBitacora', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_eliminacion', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.material')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eliminaciones_realizadas', to='usuario.usuario')),
            ],
        ),
    ]
