# Generated by Django 5.2 on 2025-12-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmaco',
            fields=[
                ('idfarmacos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('presentacion', models.CharField(max_length=15)),
                ('tipo_farmaco', models.CharField(max_length=15)),
                ('via_administracion', models.CharField(max_length=15)),
                ('consentracion', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
