# Generated by Django 5.2 on 2025-12-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmaco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmaco',
            name='tipo_farmaco',
            field=models.CharField(max_length=25),
        ),
    ]
