# Generated by Django 5.2 on 2026-07-22 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmaco', '0002_alter_farmaco_tipo_farmaco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmaco',
            name='consentracion',
        ),
        migrations.RemoveField(
            model_name='farmaco',
            name='via_administracion',
        ),
        migrations.AddField(
            model_name='farmaco',
            name='fecha_abierto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmaco',
            name='fecha_llegada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
