# Generated by Django 5.2 on 2026-07-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmaco', '0003_remove_farmaco_consentracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmaco',
            name='fecha_llegada',
            field=models.DateField(),
        ),
    ]
