# Generated by Django 5.2 on 2026-09-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmaco', '0004_alter_farmaco_fecha_llegada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmaco',
            name='presentacion',
            field=models.CharField(choices=[('TABLETA', 'Tableta'), ('AMPOLLA', 'Ampolla'), ('GRANULADO', 'Granulado'), ('CAPSULA', 'Cápsula'), ('CREMA', 'Crema'), ('POMADA', 'Pomada'), ('PASTA', 'Pasta'), ('GEL', 'Gel'), ('SOLUCION_ORAL', 'Solución oral'), ('SUSPENSION_ORAL', 'Suspensión oral'), ('EMULSION_ORAL', 'Emulsión oral'), ('JARABE', 'Jarabe'), ('VIAL', 'Vial'), ('INFUSION', 'Infusión')], max_length=30),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='tipo_farmaco',
            field=models.CharField(choices=[('ANESTESICO_GENERAL', 'Anestésico general'), ('ANESTESICO_LOCAL', 'Anestésico local'), ('SEDANTE', 'Sedante / Tranquilizante'), ('ANALGESICO_OPIOIDE', 'Analgésico opioide'), ('ANALGESICO_AINE', 'Analgésico AINE'), ('ANALGESICO_NEUROMODULADOR', 'Analgésico adyuvante / Neuromodulador'), ('INHIBIDOR_ENZIMATICO', 'Inhibidor enzimático experimental'), ('MODULADOR_CANALES', 'Modulador de canales iónicos'), ('ANTAGONISTA_TRP', 'Antagonista de receptores TRP'), ('AGENTE_ALGESIOGENICO', 'Agente algesiogénico / Inductor de dolor')], max_length=25),
        ),
    ]
