# Generated by Django 5.2 on 2026-01-02 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmaco', '0002_alter_farmaco_tipo_farmaco'),
        ('protocoloExperimental', '0001_initial'),
        ('usuario', '0012_remove_sesionexperimental_farmaco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionExperimental',
            fields=[
                ('idsesionExperimental', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nombre_experimento', models.CharField(max_length=45)),
                ('observaciones', models.CharField(max_length=45)),
                ('numero_mediciones', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('farmaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmaco.farmaco')),
                ('protocolo_experimental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocoloExperimental.protocoloexperimental')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoMedicion',
            fields=[
                ('idresultadoMedicion', models.AutoField(primary_key=True, serialize=False)),
                ('medicion_obtenida', models.CharField(max_length=20)),
                ('numero_medicion', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('sesion_experimental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesionExperimental.sesionexperimental')),
            ],
        ),
    ]
