# Generated by Django 5.2 on 2026-01-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesionExperimental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionexperimental',
            name='intervaloTemp1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesionexperimental',
            name='intervaloTemp2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesionexperimental',
            name='noMediones1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesionexperimental',
            name='noMediones2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
