# Generated by Django 5.2 on 2026-01-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesionExperimental', '0002_sesionexperimental_intervalotemp1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesionexperimental',
            old_name='noMediones1',
            new_name='noMediciones2',
        ),
        migrations.RemoveField(
            model_name='sesionexperimental',
            name='noMediones2',
        ),
        migrations.AddField(
            model_name='sesionexperimental',
            name='noMediciones1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sesionexperimental',
            name='intervaloTemp1',
            field=models.IntegerField(default=0),
        ),
    ]
