# Generated by Django 5.2 on 2026-01-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesionExperimental', '0003_rename_nomediones1_sesionexperimental_nomediciones2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesionexperimental',
            name='numero_mediciones',
        ),
    ]
