# Generated by Django 5.2 on 2026-01-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesionExperimental', '0004_remove_sesionexperimental_numero_mediciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadomedicion',
            name='confianza',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='nivelDolor',
            field=models.IntegerField(choices=[(1, 'Sin dolor'), (2, 'Dolor leve'), (3, 'Dolor intenso')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='noRaton',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
