# Generated by Django 5.2 on 2026-01-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesionExperimental', '0005_resultadomedicion_confianza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadomedicion',
            name='medicion_obtenida',
        ),
    ]
