# Generated by Django 5.2 on 2026-03-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesionExperimental', '0006_remove_resultadomedicion_medicion_obtenida'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionexperimental',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
