# Generated by Django 5.2 on 2026-05-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesionExperimental', '0007_sesionexperimental_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadomedicion',
            name='estado_medicion',
            field=models.BooleanField(default=True),
        ),
    ]
