# Generated by Django 5.2 on 2026-05-22 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotesAnimales', '0004_remove_loteanimales_observaciones_and_more'),
        ('sesionExperimental', '0008_resultadomedicion_estado_medicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadomedicion',
            name='bigotes_nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='cachetes_nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='nariz_nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='ojos_nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='orejas_nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sesionexperimental',
            name='loteAnimal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lotesAnimales.loteanimales'),
        ),
    ]
