# Generated by Django 5.2 on 2026-07-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesionExperimental', '0009_resultadomedicion_bigotes_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadomedicion',
            name='nivelDolor',
            field=models.IntegerField(choices=[(0, 'Sin dolor'), (1, 'Dolor leve'), (2, 'Dolor intenso')]),
        ),
    ]
