# Generated by Django 5.2 on 2026-07-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesionExperimental', '0010_alter_resultadomedicion_niveldolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadomedicion',
            name='confianza_cachetes',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='confianza_nariz',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='confianza_ojos',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='confianza_orejas',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
