# Generated by Django 5.2 on 2026-07-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesionExperimental', '0011_resultadomedicion_confianza_cachetes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadomedicion',
            name='promedio_confianza',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='promedio_nivel',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
