# Generated by Django 5.2 on 2026-07-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesionExperimental', '0012_resultadomedicion_promedio_confianza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadomedicion',
            name='bigotes_nivel',
        ),
        migrations.RemoveField(
            model_name='resultadomedicion',
            name='cachetes_nivel',
        ),
        migrations.RemoveField(
            model_name='resultadomedicion',
            name='confianza_cachetes',
        ),
        migrations.RemoveField(
            model_name='resultadomedicion',
            name='confianza_nariz',
        ),
        migrations.RemoveField(
            model_name='resultadomedicion',
            name='confianza_ojos',
        ),
        migrations.RemoveField(
            model_name='resultadomedicion',
            name='confianza_orejas',
        ),
        migrations.RemoveField(
            model_name='resultadomedicion',
            name='nariz_nivel',
        ),
        migrations.RemoveField(
            model_name='resultadomedicion',
            name='ojos_nivel',
        ),
        migrations.RemoveField(
            model_name='resultadomedicion',
            name='orejas_nivel',
        ),
        migrations.RemoveField(
            model_name='resultadomedicion',
            name='promedio_confianza',
        ),
        migrations.RemoveField(
            model_name='resultadomedicion',
            name='promedio_nivel',
        ),
    ]
