# Generated by Django 5.2 on 2026-08-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesionExperimental', '0013_remove_resultadomedicion_bigotes_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadomedicion',
            name='bigotes_nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='cachetes_nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='confianza_cachetes',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='confianza_nariz',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='confianza_ojos',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='confianza_orejas',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='nariz_nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='ojos_nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='orejas_nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='promedio_confianza',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='resultadomedicion',
            name='promedio_nivel',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
