# Generated by Django 5.2 on 2026-02-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesionActiva', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividadusuario',
            old_name='fechaFin',
            new_name='ultimaActividad',
        ),
        migrations.AddField(
            model_name='actividadusuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='actividadusuario',
            name='fechaInicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
