# Generated by Django 5.2 on 2026-02-16 00:00

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesionActiva', '0002_rename_fechafin_actividadusuario_ultimaactividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadusuario',
            name='fechaInicio',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now),
        ),
    ]
