# Generated by Django 5.2 on 2026-02-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesionActiva', '0004_alter_actividadusuario_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadusuario',
            name='fechaInicio',
            field=models.DateTimeField(),
        ),
    ]
