# Generated by Django 5.2 on 2026-02-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesionActiva', '0006_alter_actividadusuario_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadusuario',
            name='fechaInicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='actividadusuario',
            name='ultimaActividad',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
