# Generated by Django 5.2 on 2025-11-05 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmaco',
            fields=[
                ('idfarmacos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('presentacion', models.CharField(max_length=15)),
                ('tipo_farmaco', models.CharField(max_length=15)),
                ('via_administracion', models.CharField(max_length=15)),
                ('consentracion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocoloExperimental',
            fields=[
                ('idprotocolosExperimentales', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_protocolo', models.CharField(max_length=45)),
                ('objetivo_protocolo', models.CharField(max_length=45)),
                ('descripcion_protocolo', models.CharField(max_length=100)),
                ('consideraciones_eticas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=45)),
                ('contacto', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=25)),
                ('direccion', models.CharField(max_length=45)),
                ('tipo_insumo', models.CharField(max_length=15)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idmateriales', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('material_fabricacion', models.CharField(max_length=45)),
                ('piezas_disponibles', models.IntegerField()),
                ('uso', models.CharField(max_length=45)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='SesionExperimental',
            fields=[
                ('idsesionExperimental', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nombre_experimento', models.CharField(max_length=45)),
                ('observaciones', models.CharField(max_length=45)),
                ('numero_mediciones', models.IntegerField()),
                ('farmaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.farmaco')),
                ('protocolo_experimental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.protocoloexperimental')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoMedicion',
            fields=[
                ('idresultadoMedicion', models.AutoField(primary_key=True, serialize=False)),
                ('medicion_obtenida', models.CharField(max_length=20)),
                ('numero_medicion', models.IntegerField()),
                ('sesion_experimental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.sesionexperimental')),
            ],
        ),
        migrations.CreateModel(
            name='SustanciaExperimental',
            fields=[
                ('idsustanciaExperimental', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sustancia', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=25)),
                ('consentracion', models.CharField(max_length=15)),
                ('presentacion', models.CharField(max_length=45)),
                ('unidad_medida', models.CharField(max_length=45)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='protocoloexperimental',
            name='sustancia_experimental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.sustanciaexperimental'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuarios', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido_paterno', models.CharField(max_length=45)),
                ('apellido_materno', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=45)),
                ('contrasenia', models.CharField(max_length=128)),
                ('fecha_registro', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sesionexperimental',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
        migrations.CreateModel(
            name='LoteAnimales',
            fields=[
                ('idlotesAnimales', models.AutoField(primary_key=True, serialize=False)),
                ('especie', models.CharField(max_length=15)),
                ('cantidad_animales', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
                ('peso_ingreso', models.FloatField()),
                ('condicion_experimental', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('cepa', models.CharField(max_length=15)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idcitas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(max_length=45)),
                ('protocolo_experimental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.protocoloexperimental')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
