# Generated by Django 5.2 on 2025-11-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuario_contrasenia_alter_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
    ]
