# Generated by Django 5.2 on 2025-12-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=55),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=55),
        ),
        migrations.DeleteModel(
            name='LoteAnimales',
        ),
    ]
