# Generated by Django 5.2 on 2025-12-09 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provedor', '0001_initial'),
        ('usuario', '0005_cita_is_active_farmaco_is_active_material_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustanciaexperimental',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provedor.proveedor'),
        ),
        migrations.AlterField(
            model_name='material',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provedor.proveedor'),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
