# Generated by Django 5.2 on 2025-12-10 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmaco', '0001_initial'),
        ('usuario', '0006_alter_sustanciaexperimental_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionexperimental',
            name='farmaco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmaco.farmaco'),
        ),
        migrations.DeleteModel(
            name='Farmaco',
        ),
    ]
