# Generated by Django 5.2 on 2025-12-11 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_sesionexperimental_farmaco_delete_farmaco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
