# Generated by Django 5.2 on 2025-12-13 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustanciaExperimental', '0001_initial'),
        ('usuario', '0008_delete_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocoloexperimental',
            name='sustancia_experimental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sustanciaExperimental.sustanciaexperimental'),
        ),
        migrations.DeleteModel(
            name='SustanciaExperimental',
        ),
    ]
