# Generated by Django 5.2 on 2025-12-18 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloExperimental', '0001_initial'),
        ('usuario', '0009_alter_protocoloexperimental_sustancia_experimental_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='protocolo_experimental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocoloExperimental.protocoloexperimental'),
        ),
        migrations.AlterField(
            model_name='sesionexperimental',
            name='protocolo_experimental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocoloExperimental.protocoloexperimental'),
        ),
        migrations.DeleteModel(
            name='ProtocoloExperimental',
        ),
    ]
