# Generated by Django 5.2 on 2025-12-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_cita_protocolo_experimental_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
