# Generated by Django 5.2 on 2026-01-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_delete_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesionexperimental',
            name='farmaco',
        ),
        migrations.RemoveField(
            model_name='sesionexperimental',
            name='protocolo_experimental',
        ),
        migrations.RemoveField(
            model_name='sesionexperimental',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ResultadoMedicion',
        ),
        migrations.DeleteModel(
            name='SesionExperimental',
        ),
    ]
