# Generated by Django 5.2 on 2026-01-21 18:57
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_remove_sesionexperimental_farmaco_and_more'),  # ajusta este número
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

