# Generated by Django 5.2 on 2026-01-21 19:17
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_auto_20260121_1257'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [    ]
