# Generated by Django 5.2 on 2026-03-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_migrar_usuarios_de_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificaciones',
            fields=[
                ('idNotificaciones', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Cita', 'Cita'), ('SesionActiva', 'Sesion Activa')], max_length=50)),
                ('id_objeto', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuario.usuario')),
            ],
            options={
                'db_table': 'Notificaciones',
            },
        ),
    ]
