# Generated by Django 5.2 on 2026-03-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_notificaciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notificaciones',
            new_name='Notificacion',
        ),
    ]
