# Generated by Django 5.2 on 2025-12-25 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocoloExperimental', '0001_initial'),
        ('usuario', '0011_delete_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idcitas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(max_length=45)),
                ('is_active', models.BooleanField(default=True)),
                ('protocolo_experimental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocoloExperimental.protocoloexperimental')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
