# Generated by Django 5.2 on 2026-01-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Asignada', 'Asignar'), ('Cancelada', 'Cancelar'), ('Finalizada', 'Finalizar')], max_length=15),
        ),
    ]
