# Generated by Django 5.2 on 2026-03-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_alter_cita_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='salaLaboratorio',
            fields=[
                ('idSalaLaboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default=None, null=True)),
                ('enUso', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
