# Generated by Django 5.2 on 2026-03-15 14:14

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0004_salalaboratorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='hora',
        ),
        migrations.AddField(
            model_name='cita',
            name='fechaFin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cita',
            name='fechaInicio',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 14, 9, 0)),
        ),
        migrations.AddField(
            model_name='cita',
            name='sala_laboratorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cita.salalaboratorio'),
        ),
    ]
