# Generated by Django 5.2 on 2026-03-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0005_remove_cita_fecha_remove_cita_hora_cita_fechafin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fechaFin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fechaInicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='sala_laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.salalaboratorio'),
        ),
    ]
