# Generated by Django 5.2 on 2026-08-18 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0006_alter_cita_fechafin_alter_cita_fechainicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fechaFin',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='fechaInicio',
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha',
            field=models.DateField(default=datetime.date(2026, 8, 18)),
        ),
        migrations.AddField(
            model_name='cita',
            name='horaFin',
            field=models.TimeField(default=datetime.time(18, 39, 32, 881385)),
        ),
        migrations.AddField(
            model_name='cita',
            name='horaInicio',
            field=models.TimeField(default=datetime.time(17, 39, 32, 881385)),
        ),
    ]
