# Generated by Django 5.2 on 2026-09-13 22:10

import cita.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0007_remove_cita_fechafin_remove_cita_fechainicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cita',
            name='horaFin',
            field=models.TimeField(default=cita.models.Cita.get_hora_act),
        ),
        migrations.AlterField(
            model_name='cita',
            name='horaInicio',
            field=models.TimeField(default=cita.models.Cita.get_hora_act),
        ),
    ]
