# Generated by Django 5.2 on 2026-02-04 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sesionExperimental', '0006_remove_resultadomedicion_medicion_obtenida'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaExperimental',
            fields=[
                ('idIncidencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('idSesionExperimental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesionExperimental.sesionexperimental')),
            ],
        ),
    ]
