# Generated by Django 5.2 on 2025-12-03 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0004_alter_usuario_correo_alter_usuario_matricula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteAnimales',
            fields=[
                ('idlotesAnimales', models.AutoField(primary_key=True, serialize=False)),
                ('especie', models.CharField(max_length=15)),
                ('cantidad_animales', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
                ('peso_ingreso', models.FloatField()),
                ('condicion_experimental', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('cepa', models.CharField(max_length=15)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
