# Generated by Django 5.2 on 2025-12-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotesAnimales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteanimales',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
