# Generated by Django 5.2 on 2025-12-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotesAnimales', '0002_loteanimales_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteanimales',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
