# Generated by Django 5.2 on 2026-01-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotesAnimales', '0003_alter_loteanimales_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loteanimales',
            name='observaciones',
        ),
        migrations.AlterField(
            model_name='loteanimales',
            name='especie',
            field=models.CharField(choices=[('rata', 'Rata'), ('raton', 'Ratón')], max_length=10),
        ),
        migrations.AlterField(
            model_name='loteanimales',
            name='estado',
            field=models.CharField(choices=[('sano', 'Sano'), ('experimentacion', 'En experimentación'), ('baja', 'Baja')], max_length=50),
        ),
        migrations.AlterField(
            model_name='loteanimales',
            name='genero',
            field=models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10),
        ),
    ]
