# Generated by Django 5.2 on 2026-07-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotesAnimales', '0004_remove_loteanimales_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteanimales',
            name='tratamiento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
