# Generated by Django 5.2 on 2025-12-18 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sustanciaExperimental', '0002_alter_sustanciaexperimental_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocoloExperimental',
            fields=[
                ('idprotocolosExperimentales', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_protocolo', models.CharField(max_length=45)),
                ('objetivo_protocolo', models.CharField(max_length=45)),
                ('descripcion_protocolo', models.CharField(max_length=100)),
                ('consideraciones_eticas', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sustancia_experimental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sustanciaExperimental.sustanciaexperimental')),
            ],
        ),
    ]
