# Generated by Django 5.2 on 2026-01-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloExperimental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='protocoloexperimental',
            table='ProtocoloExperimental',
        ),
    ]
