# Generated by Django 5.2 on 2026-07-22 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloExperimental', '0002_alter_protocoloexperimental_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoloexperimental',
            name='numero_aprobacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='protocoloexperimental',
            name='vigencia',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
