# Generated by Django 5.2 on 2026-07-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloExperimental', '0003_protocoloexperimental_numero_aprobacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocoloexperimental',
            name='vigencia',
            field=models.DateField(),
        ),
    ]
